In [1]:
try: 
    x=int(input("Enter the number: "))
    print(x)
except:
    print("Please enter the integer")
finally:
    print("number input done")

23
number input done


In [5]:
f=open("C:/Users/harsh/OneDrive/Desktop/Java Program/Jcoo.txt","r")
f.readline()

'This resource begins with a general description of essay writing and moves to a discussion of common essay genres students may encounter across the curriculum. The four genres of essays (description, narration, exposition, and argumentation) are common paper assignments you may encounter in your writing classes. Although these genres, also known as the modes of discourse, have been criticized by some composition scholars, the Purdue OWL recognizes the wide spread use of these genres and students’ need to understand and produce these types of essays. We hope these resources will help.'

In [7]:
fw=open("Apll.txt","w")
fw.write("Hello, I am Harsh")
fw.close

<function TextIOWrapper.close()>

In [2]:
f=open("jah.txt")
lines_list=f.readlines()

In [11]:
# for i in range(len(lines_list)):
    # print(lines_list.split(","))[0]

AttributeError: 'list' object has no attribute 'split'

In [6]:
[lines_list[i].split(",")[0] for i in range(len(lines_list))]

['["Harsh Mishra', '"Piyush Sunno']

In [15]:
import numpy as np
x=np.array([1,2,3,4,5],dtype="int64")

print()
print("x= ",x)
print()



x=  [1 2 3 4 5]



In [16]:
print("x has dimensions:",x.shape)
print("x has type",type(x))
print("x has dimensions:",x.dtype)


x has dimensions: (5,)
x has type <class 'numpy.ndarray'>
x has dimensions: int64


In [23]:
x2d=np.array([[4,6,2],[8,0,7],[2,4,3]])
print(x2d)
print(x2d.shape)
print(x2d.size)

[[4 6 2]
 [8 0 7]
 [2 4 3]]
(3, 3)
9


In [19]:
for triangles in range(4):
    for vertices in range(3):
        for coord in range(2):
            x=int(input())
            y= int(input())

In [22]:
print(x)
print(y)

1
1


In [24]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [28]:
z=np.eye(5)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [31]:
# this for the range 1st indicates the where to start and  2nd till where and lastly how much we have skip 
np.arange(2,50,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [32]:
r=np.linspace(0,10,5)
print(r)

[ 0.   2.5  5.   7.5 10. ]


In [35]:
w=np.random.random((8,2))
print(w)

[[0.61991948 0.61974903]
 [0.01105846 0.24954638]
 [0.83169191 0.85656615]
 [0.60269898 0.66327492]
 [0.32892372 0.60221815]
 [0.8547422  0.2534068 ]
 [0.4063226  0.85463329]
 [0.68303302 0.60942591]]


In [36]:
# it will generates the random int number
np.random.randint(2,7)

3

In [37]:
# to create the array of random int 
np.random.randint(4,10,size=(3,4))

array([[9, 4, 4, 9],
       [6, 7, 4, 8],
       [9, 4, 5, 8]])

In [8]:
import numpy as np
# reshape is use for the change the shape of the array
# reshape is the important function
np.random.seed(23)
v=np.random.randint(2,30,size=(10))
print(v)
np.reshape(v,(2,5))

[21  8 10 11 24 10 15 14 29  9]


array([[21,  8, 10, 11, 24],
       [10, 15, 14, 29,  9]])

In [5]:
import numpy as np
b=np.arange(2,33,2).reshape(4,4)
print(b)
# np.delete(b,[0,2])
np.delete(b,[0],axis=1)
np.delete(b,[0],axis=0)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [14]:
x=np.linspace(2,32,16,dtype=np.int64)
print(x)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]


In [7]:
# we create a rank 1 ndarray
x=np.array([1,2,3,4,5])

#We create a rank 2 ndarray
y=np.array([[1,2,3],[4,5,6]])
print(y)

print(np.append(x,[4,6,87,8]))
np.append(y,[[43,33,44]],axis=0)

[[1 2 3]
 [4 5 6]]
[ 1  2  3  4  5  4  6 87  8]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [43, 33, 44]])

In [8]:
np.append(y,[[32],[56]],axis=1)

array([[ 1,  2,  3, 32],
       [ 4,  5,  6, 56]])

In [11]:
# To attached 2 array we can use vstack or hstack
j=np.array([1,2])
# vstack means the vertical stack
k=np.array([[3,4],[6,4]])
np.vstack((j,k))

array([[1, 2],
       [3, 4],
       [6, 4]])

In [19]:
# slicing in numpy
v=np.array([3,4,5,6,3,8,0])
print(v)
print(v[-1:])

[3 4 5 6 3 8 0]
[0]


In [26]:
# for 2d array
r=np.array([[4,5,6,3],[2,9,19,3],[21,54,23,54]])
print(r)
print(r[0:2,0:2])

[[ 4  5  6  3]
 [ 2  9 19  3]
 [21 54 23 54]]
[[4 5]
 [2 9]]


In [27]:
# boolean indexing

# this is the not for numpy eqn 
u=np.array([2,5,4,8,0,76,9])
[u[i] for i in range(len(u)) if u[i]>5]

[8, 76, 9]

In [29]:
# this is used in numpy boolean expression
u[u%2==0]

array([ 2,  4,  8,  0, 76])

In [32]:
# In numpy "and " is not used as well "or " is not used instead of this we use bitwise array"&,|"
print(u[(u%2==0) & (u<5)])

[2 4 0]


In [36]:
np.sort(u)
# to print in the desencding order wecan use
np.flip(np.sort(u))

array([76,  9,  8,  5,  4,  2,  0])

In [49]:
y=np.random.randint(1,100,size=(5,5))
print(y)
print(np.sort(y))
# row wise sorting
# np.sort(y,axis=0)
# col wise sorting 
np.sort(y,axis=1)

[[39 78 79 35 47]
 [93 41 82 34 36]
 [33 90 57 67 28]
 [22 86 49  7  8]
 [63 22 51 16 92]]
[[35 39 47 78 79]
 [34 36 41 82 93]
 [28 33 57 67 90]
 [ 7  8 22 49 86]
 [16 22 51 63 92]]


array([[35, 39, 47, 78, 79],
       [34, 36, 41, 82, 93],
       [28, 33, 57, 67, 90],
       [ 7,  8, 22, 49, 86],
       [16, 22, 51, 63, 92]])

In [42]:
# to only print the unique item
np.unique(u)

array([ 0,  2,  4,  5,  8,  9, 76])

In [43]:
z=np.arange(1,26).reshape(5,5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [46]:
z[z%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [47]:
# Arithematic operator in numpy
z+5


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [50]:
print(z+y)

[[ 40  80  82  39  52]
 [ 99  48  90  43  46]
 [ 44 102  70  81  43]
 [ 38 103  67  26  28]
 [ 84  44  74  40 117]]


In [53]:
# broadcasting
import numpy as harsh
x=harsh.array([1,2,4])
print(x)
y=harsh.array([[1,2,3],[5,7,4]])
z=harsh.array([[1],[2],[3]])
x+y

[1 2 4]


array([[2, 4, 7],
       [6, 9, 8]])

In [55]:
# for transpose
y.T # T satnds of transpose

array([[1, 5],
       [2, 7],
       [3, 4]])

In [5]:
import numpy as np
x=np.zeros((4,4))
print(x)
x=(x + np.array([1,2,3,4]))

print(x)
print(x.T)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [7]:
y=np.arange(32)
y=y.reshape((4,8))
print(y)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [8]:
np.sum(y,axis=1)

array([ 28,  92, 156, 220])